repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ['--fix=lf']
        description: Forces to replace line ending by the UNIX 'lf' character.
  - repo: local
    hooks:
      - id: flake8
        name: Check flake8 syntax
        entry: flake8 readonly tests
        pass_filenames: false
        language: system
        types: [python]
      - id: isort
        name: Sort imports alphabetically
        entry: isort readonly tests --check-only --diff
        pass_filenames: false
        language: system
        types: [python]
      - id: mypy
        name: Check mypy static types match
        entry: mypy -p readonly
        pass_filenames: false
        language: system
        types: [python]
      - id: black
        name: Run black code formatter
        entry: black readonly --check
        pass_filenames: false
        language: system
        types: [python]
      - id: rstcheck
        name: RChecks syntax of reStructuredText
        entry: rstcheck README.rst
        pass_filenames: false
        language: system
        types: [python]
